Parse.Cloud.define("initializeNewUser", function (request, response) {
    console.log('Start initializeNewUser');
    var user = request.user;
    console.log('Found new user: ' + user.get("name"));
    var ACL = new Parse.ACL(user);
    var unsavedItemObjects = [];

    var attributes = new Parse.Object("ListAttributes");
    attributes.set('author', user);
    attributes.set('listAttributesID', 1);
    attributes.set('name', 'Genoa');
    attributes.set('nameLowercase', 'genoa');
    attributes.set("isDefaultAttributes", false);
    attributes.set("isChecked", false);
    attributes.set("startColor", -11761266);
    attributes.set("endColor", -15576746);
    attributes.set("textColor", -1);
    attributes.set("textSize", 17);
    attributes.set("isBold", true);
    attributes.set("horizontalPaddingInDp", 15);
    attributes.set("verticalPaddingInDp", 15);
    attributes.set("isTransparent", false);
    attributes.set("localUuid", '');
    attributes.set("isAttributesDirty", false);
    attributes.set("isMarkedForDeletion", false);
    attributes.setACL(ACL);
    unsavedItemObjects[0] = attributes;

    var attributes = new Parse.Object("ListAttributes");
    attributes.set('author', user);
    attributes.set('listAttributesID', 2);
    attributes.set('name', 'Opal');
    attributes.set('nameLowercase', 'opal');
    attributes.set("isDefaultAttributes", false);
    attributes.set("isChecked", false);
    attributes.set("startColor", -3416876);
    attributes.set("endColor", -7231843);
    attributes.set("textColor", -16777216);
    attributes.set("textSize", 17);
    attributes.set("isBold", false);
    attributes.set("horizontalPaddingInDp", 15);
    attributes.set("verticalPaddingInDp", 15);
    attributes.set("isTransparent", false);
    attributes.set("localUuid", '');
    attributes.set("isAttributesDirty", false);
    attributes.set("isMarkedForDeletion", false);
    attributes.setACL(ACL);
    unsavedItemObjects[1] = attributes;

    var attributes = new Parse.Object("ListAttributes");
    attributes.set('author', user);
    attributes.set('listAttributesID', 3);
    attributes.set('name', 'Shades of Blue');
    attributes.set('nameLowercase', 'shades of blue');
    attributes.set("isDefaultAttributes", false);
    attributes.set("isChecked", false);
    attributes.set("startColor", -5777934);
    attributes.set("endColor", -10841921);
    attributes.set("textColor", -16777216);
    attributes.set("textSize", 17);
    attributes.set("isBold", false);
    attributes.set("horizontalPaddingInDp", 15);
    attributes.set("verticalPaddingInDp", 15);
    attributes.set("isTransparent", false);
    attributes.set("localUuid", '');
    attributes.set("isAttributesDirty", false);
    attributes.set("isMarkedForDeletion", false);
    attributes.setACL(ACL);
    unsavedItemObjects[2] = attributes;

    var attributes = new Parse.Object("ListAttributes");
    attributes.set('author', user);
    attributes.set('listAttributesID', 4);
    attributes.set('name', 'Off White');
    attributes.set('nameLowercase', 'off white');
    attributes.set("isDefaultAttributes", false);
    attributes.set("isChecked", false);
    attributes.set("startColor", -1);
    attributes.set("endColor", -2436147);
    attributes.set("textColor", -16777216);
    attributes.set("textSize", 17);
    attributes.set("isBold", false);
    attributes.set("horizontalPaddingInDp", 15);
    attributes.set("verticalPaddingInDp", 5);
    attributes.set("isTransparent", true);
    attributes.set("localUuid", '');
    attributes.set("isAttributesDirty", false);
    attributes.set("isMarkedForDeletion", false);
    attributes.setACL(ACL);
    unsavedItemObjects[3] = attributes;


    var attributes = new Parse.Object("ListAttributes");
    attributes.set('author', user);
    attributes.set('listAttributesID', 5);
    attributes.set('name', 'Whiskey');
    attributes.set('nameLowercase', 'whiskey');
    attributes.set("isDefaultAttributes", false);
    attributes.set("isChecked", false);
    attributes.set("startColor", -1463187);
    attributes.set("endColor", -5408448);
    attributes.set("textColor", -1);
    attributes.set("textSize", 17);
    attributes.set("isBold", false);
    attributes.set("horizontalPaddingInDp", 15);
    attributes.set("verticalPaddingInDp", 15);
    attributes.set("isTransparent", false);
    attributes.set("localUuid", '');
    attributes.set("isAttributesDirty", false);
    attributes.set("isMarkedForDeletion", false);
    attributes.setACL(ACL);
    unsavedItemObjects[4] = attributes;

    var attributes = new Parse.Object("ListAttributes");
    attributes.set('author', user);
    attributes.set('listAttributesID', 6);
    attributes.set('name', 'Shakespeare');
    attributes.set('nameLowercase', 'shakespeare');
    attributes.set("isDefaultAttributes", false);
    attributes.set("isChecked", false);
    attributes.set("startColor", -9189933);
    attributes.set("endColor", -13595234);
    attributes.set("textColor", -1);
    attributes.set("textSize", 17);
    attributes.set("isBold", false);
    attributes.set("horizontalPaddingInDp", 15);
    attributes.set("verticalPaddingInDp", 15);
    attributes.set("isTransparent", false);
    attributes.set("localUuid", '');
    attributes.set("isAttributesDirty", false);
    attributes.set("isMarkedForDeletion", false);
    attributes.setACL(ACL);
    unsavedItemObjects[5] = attributes;

    var attributes = new Parse.Object("ListAttributes");
    attributes.set('author', user);
    attributes.set('listAttributesID', 7);
    attributes.set('name', 'Sorbus');
    attributes.set('nameLowercase', 'sorbus');
    attributes.set("isDefaultAttributes", false);
    attributes.set("isChecked", false);
    attributes.set("startColor", -1019301);
    attributes.set("endColor", -4441055);
    attributes.set("textColor", -1);
    attributes.set("textSize", 17);
    attributes.set("isBold", false);
    attributes.set("horizontalPaddingInDp", 15);
    attributes.set("verticalPaddingInDp", 15);
    attributes.set("isTransparent", false);
    attributes.set("localUuid", '');
    attributes.set("isAttributesDirty", false);
    attributes.set("isMarkedForDeletion", false);
    attributes.setACL(ACL);
    unsavedItemObjects[6] = attributes;

    var attributes = new Parse.Object("ListAttributes");
    attributes.set('author', user);
    attributes.set('listAttributesID', 8);
    attributes.set('name', 'Dark Khaki');
    attributes.set('nameLowercase', 'dark khaki');
    attributes.set("isDefaultAttributes", false);
    attributes.set("isChecked", false);
    attributes.set("startColor", -3222907);
    attributes.set("endColor", -6578347);
    attributes.set("textColor", -1);
    attributes.set("textSize", 17);
    attributes.set("isBold", false);
    attributes.set("horizontalPaddingInDp", 15);
    attributes.set("verticalPaddingInDp", 15);
    attributes.set("isTransparent", false);
    attributes.set("localUuid", '');
    attributes.set("isAttributesDirty", false);
    attributes.set("isMarkedForDeletion", false);
    attributes.setACL(ACL);
    unsavedItemObjects[7] = attributes;

    var attributes = new Parse.Object("ListAttributes");
    attributes.set('author', user);
    attributes.set('listAttributesID', 9);
    attributes.set('name', 'Lemon Chiffon');
    attributes.set('nameLowercase', 'lemon chiffon');
    attributes.set("isDefaultAttributes", false);
    attributes.set("isChecked", false);
    attributes.set("startColor", -131875);
    attributes.set("endColor", -1842516);
    attributes.set("textColor", -16777216);
    attributes.set("textSize", 17);
    attributes.set("isBold", false);
    attributes.set("horizontalPaddingInDp", 15);
    attributes.set("verticalPaddingInDp", 15);
    attributes.set("isTransparent", false);
    attributes.set("localUuid", '');
    attributes.set("isAttributesDirty", false);
    attributes.set("isMarkedForDeletion", false);
    attributes.setACL(ACL);
    unsavedItemObjects[8] = attributes;

    var attributes = new Parse.Object("ListAttributes");
    attributes.set('author', user);
    attributes.set('listAttributesID', 10);
    attributes.set('name', 'Paprika');
    attributes.set('nameLowercase', 'paprika');
    attributes.set("isDefaultAttributes", false);
    attributes.set("isChecked", false);
    attributes.set("startColor", -6732462);
    attributes.set("endColor", -10548202);
    attributes.set("textColor", -1);
    attributes.set("textSize", 17);
    attributes.set("isBold", false);
    attributes.set("horizontalPaddingInDp", 15);
    attributes.set("verticalPaddingInDp", 15);
    attributes.set("isTransparent", false);
    attributes.set("localUuid", '');
    attributes.set("isAttributesDirty", false);
    attributes.set("isMarkedForDeletion", false);
    attributes.setACL(ACL);
    unsavedItemObjects[9] = attributes;

    var attributes = new Parse.Object("ListAttributes");
    attributes.set('author', user);
    attributes.set('listAttributesID', 11);
    attributes.set('name', 'Medium Wood');
    attributes.set('nameLowercase', 'medium wood');
    attributes.set("isDefaultAttributes", false);
    attributes.set("isChecked", false);
    attributes.set("startColor", -4216203);
    attributes.set("endColor", -7703994);
    attributes.set("textColor", -1);
    attributes.set("textSize", 17);
    attributes.set("isBold", false);
    attributes.set("horizontalPaddingInDp", 15);
    attributes.set("verticalPaddingInDp", 15);
    attributes.set("isTransparent", false);
    attributes.set("localUuid", '');
    attributes.set("isAttributesDirty", false);
    attributes.set("isMarkedForDeletion", false);
    attributes.setACL(ACL);
    unsavedItemObjects[10] = attributes;

    var attributes = new Parse.Object("ListAttributes");
    attributes.set('author', user);
    attributes.set('listAttributesID', 12);
    attributes.set('name', 'Breaker Bay');
    attributes.set('nameLowercase', 'breaker bay');
    attributes.set("isDefaultAttributes", false);
    attributes.set("isChecked", false);
    attributes.set("startColor", -9598061);
    attributes.set("endColor", -13544612);
    attributes.set("textColor", -1);
    attributes.set("textSize", 17);
    attributes.set("isBold", false);
    attributes.set("horizontalPaddingInDp", 15);
    attributes.set("verticalPaddingInDp", 15);
    attributes.set("isTransparent", false);
    attributes.set("localUuid", '');
    attributes.set("isAttributesDirty", false);
    attributes.set("isMarkedForDeletion", false);
    attributes.setACL(ACL);
    unsavedItemObjects[11] = attributes;

    var attributes = new Parse.Object("ListAttributes");
    attributes.set('author', user);
    attributes.set('listAttributesID', 13);
    attributes.set('name', 'Sandrift');
    attributes.set('nameLowercase', 'sandrift');
    attributes.set("isDefaultAttributes", false);
    attributes.set("isChecked", false);
    attributes.set("startColor", -3426915);
    attributes.set("endColor", -7176084);
    attributes.set("textColor", -1);
    attributes.set("textSize", 17);
    attributes.set("isBold", false);
    attributes.set("horizontalPaddingInDp", 15);
    attributes.set("verticalPaddingInDp", 15);
    attributes.set("isTransparent", false);
    attributes.set("localUuid", '');
    attributes.set("isAttributesDirty", false);
    attributes.set("isMarkedForDeletion", false);
    attributes.setACL(ACL);
    unsavedItemObjects[12] = attributes;

    var attributes = new Parse.Object("ListAttributes");
    attributes.set('author', user);
    attributes.set('listAttributesID', 14);
    attributes.set('name', 'Pale Brown');
    attributes.set('nameLowercase', 'pale brown');
    attributes.set("isDefaultAttributes", false);
    attributes.set("isChecked", false);
    attributes.set("startColor", -5466772);
    attributes.set("endColor", -9413575);
    attributes.set("textColor", -1);
    attributes.set("textSize", 17);
    attributes.set("isBold", false);
    attributes.set("horizontalPaddingInDp", 15);
    attributes.set("verticalPaddingInDp", 15);
    attributes.set("isTransparent", false);
    attributes.set("localUuid", '');
    attributes.set("isAttributesDirty", false);
    attributes.set("isMarkedForDeletion", false);
    attributes.setACL(ACL);
    unsavedItemObjects[13] = attributes;

    var attributes = new Parse.Object("ListAttributes");
    attributes.set('author', user);
    attributes.set('listAttributesID', 15);
    attributes.set('name', 'Seagull');
    attributes.set('nameLowercase', 'seagull');
    attributes.set("isDefaultAttributes", false);
    attributes.set("isChecked", false);
    attributes.set("startColor", -7021334);
    attributes.set("endColor", -11624277);
    attributes.set("textColor", -16777216);
    attributes.set("textSize", 17);
    attributes.set("isBold", false);
    attributes.set("horizontalPaddingInDp", 15);
    attributes.set("verticalPaddingInDp", 15);
    attributes.set("isTransparent", false);
    attributes.set("localUuid", '');
    attributes.set("isAttributesDirty", false);
    attributes.set("isMarkedForDeletion", false);
    attributes.setACL(ACL);
    unsavedItemObjects[14] = attributes;

    var attributes = new Parse.Object("ListAttributes");
    attributes.set('author', user);
    attributes.set('listAttributesID', 16);
    attributes.set('name', 'Beige');
    attributes.set('nameLowercase', 'beige');
    attributes.set("isDefaultAttributes", false);
    attributes.set("isChecked", false);
    attributes.set("startColor", -65794);
    attributes.set("endColor", -2893630);
    attributes.set("textColor", -16777216);
    attributes.set("textSize", 17);
    attributes.set("isBold", false);
    attributes.set("horizontalPaddingInDp", 15);
    attributes.set("verticalPaddingInDp", 15);
    attributes.set("isTransparent", false);
    attributes.set("localUuid", '');
    attributes.set("isAttributesDirty", false);
    attributes.set("isMarkedForDeletion", false);
    attributes.setACL(ACL);
    unsavedItemObjects[15] = attributes;

    var attributes = new Parse.Object("ListAttributes");
    attributes.set('author', user);
    attributes.set('listAttributesID', 17);
    attributes.set('name', 'Orange');
    attributes.set('nameLowercase', 'orange');
    attributes.set("isDefaultAttributes", false);
    attributes.set("isChecked", false);
    attributes.set("startColor", -37806);
    attributes.set("endColor", -2083810);
    attributes.set("textColor", -1);
    attributes.set("textSize", 17);
    attributes.set("isBold", false);
    attributes.set("horizontalPaddingInDp", 15);
    attributes.set("verticalPaddingInDp", 15);
    attributes.set("isTransparent", false);
    attributes.set("localUuid", '');
    attributes.set("isAttributesDirty", false);
    attributes.set("isMarkedForDeletion", false);
    attributes.setACL(ACL);
    unsavedItemObjects[16] = attributes;

    var attributes = new Parse.Object("ListAttributes");
    attributes.set('author', user);
    attributes.set('listAttributesID', 18);
    attributes.set('name', 'Arsenic');
    attributes.set('nameLowercase', 'arsenic');
    attributes.set("isDefaultAttributes", false);
    attributes.set("isChecked", false);
    attributes.set("startColor", -11248537);
    attributes.set("endColor", -14867412);
    attributes.set("textColor", -1);
    attributes.set("textSize", 17);
    attributes.set("isBold", false);
    attributes.set("horizontalPaddingInDp", 15);
    attributes.set("verticalPaddingInDp", 15);
    attributes.set("isTransparent", false);
    attributes.set("localUuid", '');
    attributes.set("isAttributesDirty", false);
    attributes.set("isMarkedForDeletion", false);
    attributes.setACL(ACL);
    unsavedItemObjects[17] = attributes;

    var attributes = new Parse.Object("ListAttributes");
    attributes.set('author', user);
    attributes.set('listAttributesID', 19);
    attributes.set('name', 'Acapulco');
    attributes.set('nameLowercase', 'acapulco');
    attributes.set("isDefaultAttributes", false);
    attributes.set("isChecked", false);
    attributes.set("startColor", -7488845);
    attributes.set("endColor", -10975874);
    attributes.set("textColor", -1);
    attributes.set("textSize", 17);
    attributes.set("isBold", false);
    attributes.set("horizontalPaddingInDp", 15);
    attributes.set("verticalPaddingInDp", 15);
    attributes.set("isTransparent", false);
    attributes.set("localUuid", '');
    attributes.set("isAttributesDirty", false);
    attributes.set("isMarkedForDeletion", false);
    attributes.setACL(ACL);
    unsavedItemObjects[18] = attributes;

    console.log('Ready to save ' + unsavedItemObjects.length + ' Attributes for user: ' + user.get("name"));

    Parse.Object.saveAll(unsavedItemObjects, {
        success: function (list) {
            // All the objects were saved.
            console.log('Successfully initialized ' + list.length + ' Attributes for user: ' + user.get("name"));
            response.success(list.length);
        },
        error: function (error) {
            // An error occurred while saving one of the objects.
            console.log('An error occurred while saving one of the Attribute objects. Error code: ' + error.code + ' ' + error.message);
            response.error('An error occurred while saving one of the Attribute objects. Error code: ' + error.code + ' ' + error.message);
        }
    });
});


